# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{eyeballs}
  s.version = "0.3.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Campbell"]
  s.date = %q{2010-06-17}
  s.default_executable = %q{eyeballs}
  s.email = %q{paul@rslw.com}
  s.executables = ["eyeballs"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "CHANGELOG",
     "README.md",
     "Rakefile",
     "bin/eyeballs",
     "config.ru",
     "dist/jquery-1.4.2.min.js",
     "dist/jquery.livequery.js",
     "dist/mustache.js",
     "eyeballs.gemspec",
     "eyeballs.js.gemspec",
     "lib/eyeballs.rb",
     "lib/eyeballs/app_detector.rb",
     "lib/eyeballs/app_generator.rb",
     "lib/eyeballs/cli.rb",
     "lib/eyeballs/controller_generator.rb",
     "lib/eyeballs/model_generator.rb",
     "lib/eyeballs/scaffold_generator.rb",
     "src/jquery.o_O.couchdb.js",
     "src/jquery.o_O.dom.js",
     "src/jquery.o_O.js",
     "src/jquery.o_O.rails.js",
     "src/o_O.js",
     "src/o_O.localstorage.js",
     "templates/app_root/index.html",
     "templates/controller.js",
     "templates/model.js",
     "templates/scaffold_controller.js",
     "templates/scaffold_edit.html.mustache",
     "templates/scaffold_index.html",
     "templates/scaffold_partial.html.mustache",
     "test/unit/qunit.css",
     "test/unit/qunit.js",
     "test/unit/test_controller.html",
     "test/unit/test_dom.html",
     "test/unit/test_dom_with_callbacks.html",
     "test/unit/test_form.html",
     "test/unit/test_localstorage.html",
     "test/unit/test_model.html",
     "test/unit/test_model_with_callbacks.html",
     "test/unit/test_rails.html"
  ]
  s.has_rdoc = false
  s.homepage = %q{http://www.github.com/paulca/eyeballs.js}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A lightweight javascript MVC framework.}
  s.test_files = [
    "spec/app_generator_spec.rb",
     "spec/controller_generator_spec.rb",
     "spec/model_generator_spec.rb",
     "spec/rack_app_detector_spec.rb",
     "spec/scaffold_generator_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

