# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{eyeballs.js}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Campbell"]
  s.date = %q{2010-06-06}
  s.default_executable = %q{eyeballs}
  s.email = %q{paul@rslw.com}
  s.executables = ["eyeballs"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "CHANGELOG",
     "README.md",
     "Rakefile",
     "bin/eyeballs",
     "config.ru",
     "eyeballs.js.gemspec",
     "lib/eyeballs.rb",
     "lib/eyeballs/app_generator.rb",
     "lib/eyeballs/cli.rb",
     "lib/eyeballs/controller_generator.rb",
     "lib/eyeballs/model_generator.rb",
     "lib/eyeballs/scaffold_generator.rb",
     "templates/app_root/index.html",
     "templates/controller.js",
     "templates/model.js",
     "templates/scaffold_controller.js",
     "templates/scaffold_index.html"
  ]
  s.has_rdoc = false
  s.homepage = %q{http://www.github.com/paulca/eyeballs.js}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A lightweight javascript MVC framework.}
  s.test_files = [
    "spec/app_generator_spec.rb",
     "spec/controller_generator_spec.rb",
     "spec/model_generator_spec.rb",
     "spec/scaffold_generator_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

