require 'rubygems'
require 'thor'
require 'thor/group'
require 'active_support/inflector'

require 'eyeballs/app_detector'
require 'eyeballs/app_generator'
require 'eyeballs/cli'
require 'eyeballs/controller_generator'
require 'eyeballs/model_generator'
require 'eyeballs/scaffold_generator'
